### ISSUE TITLE
:repeat on Sequence not working

### ISSUE THREAD

**Issue by fa-m** [isaaclyman/Viano#4]
I tried to use repeat on Sequence:
`<Sequence :repeat="8">`
and got this error in console:

```
Uncaught DOMException: Failed to execute 'start' on 'AudioScheduledSourceNode': cannot call start more than once.
    at T (webpack-internal:///./node_modules/blackswan-js/dist/blackswan.js:1:6064)
    at Object.Play (webpack-internal:///./node_modules/blackswan-js/dist/blackswan.js:1:6416)
    at M (webpack-internal:///./node_modules/blackswan-js/dist/blackswan.js:1:6649)
    at Object.play (webpack-internal:///./node_modules/blackswan-js/dist/blackswan.js:1:6768)
    at VueComponent.togglePlay (eval at ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"/Users/fmalik/workspaces/tmp/viano/Viano/node_modules/.cache/cache-loader"}!./node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/Song.vue (http://localhost:8080/app.js:847:1), <anonymous>:50:19)
    at click (eval at ./node_modules/vue-loader/lib/template-compiler/index.js?{"id":"data-v-319a0ec5","hasScoped":true,"optionsId":"0","buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/components/Song.vue (http://localhost:8080/app.js:1685:1), <anonymous>:14:17)
    at invoker (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:2022:18)
    at HTMLDivElement.fn._withTask.fn._withTask (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:1821:18)
```

**Comment by isaaclyman** [comment]
Thanks for reporting that! I have a theory about why that would happen. I'll look into it.

**Comment by isaaclyman** [comment]
Okay, just committed a fix for that. You can pull latest and let me know if you still have trouble. In the meantime, I'll close this issue. Thanks again.
